## 종목별 베타 생성

Todo. 종목마다 동일 기간 데이터 건수가 상이함. 지수와도 맞지 않아 데이터 계산 오류

In [61]:
import FinanceDataReader as fdr
fdr.__version__

'0.6.0'

In [62]:
# import FinanceDataReader as fdr

# 한국거래소 상장종목 전체
df_krx = fdr.StockListing('KRX')
df_krx.head()

   Symbol   Name         Sector                     Industry
0  001040     CJ         기타 금융업                         지주회사
1  011150  CJ씨푸드      기타 식품 제조업   수산물(어묵,맛살)가공품 도매,원양수산업,수출입
2  012630    HDC         건물 건설업  토목공사,건축공사,아파트분양사업,재개발/재건축사업
3  082740  HSD엔진  일반 목적용 기계 제조업               대형선박용엔진,내연발전엔진
4  001390  KG케미칼    기초 화학물질 제조업    콘크리트혼화제, 비료, 친환경농자재, 수처리제

In [63]:
# import FinanceDataReader as fdr

# 신라젠, 2018년
df = fdr.DataReader('950170')
df.head(10)

            Close   Open   High    Low     Volume  Change
Date
2018-04-09  17000  16300  18200  16250  5780000.0  0.0429
2018-04-10  16450  16900  16900  15450  2460000.0 -0.0324
2018-04-11  16150  16800  17150  16150  1480000.0 -0.0182
2018-04-12  15300  15950  16050  15250  1190000.0 -0.0526
2018-04-13  15050  15300  15950  14800  1240000.0 -0.0163
2018-04-15  15050  15050  15050  15050        0.0  0.0000
2018-04-16  15450  15200  15850  14950  1100000.0  0.0266
2018-04-17  17050  15300  17350  15250  2300000.0  0.1036
2018-04-18  17900  17400  18100  16900  3180000.0  0.0499
2018-04-19  19050  18400  19050  17550  2740000.0  0.0642

## 시장 베타 계수  구하기

In [64]:
import numpy as np 
from statsmodels import regression 
import statsmodels.api as sm 
import matplotlib.pyplot as plt 
import math 
import pandas as pd 
import pandas_datareader as pdr

In [86]:
# 삼성전자
stock_df = fdr.DataReader('005930','2017-10-10','2018-10')
# stock_df['Close'].plot()
stock_df

            Close   Open   High    Low      Volume  Change
Date
2017-10-10  52800  53360  53640  52800  19830000.0 -0.9794
2017-10-11  54640  53600  54760  53340  12900000.0  0.0348
2017-10-12  54800  54840  55160  54100  13730000.0  0.0029
2017-10-13  54000  54540  54840  53780  12520000.0 -0.0146
2017-10-16  53920  53980  54860  53760   8960000.0 -0.0015
2017-10-17  54800  54020  55380  54000  10570000.0  0.0163
2017-10-18  54760  54820  55240  54040  10030000.0 -0.0007
2017-10-19  52980  54700  54700  52980  11970000.0 -0.0325
2017-10-20  53840  52800  54100  52800   7860000.0  0.0162
2017-10-23  54300  54600  54640  54000   8300000.0  0.0085
2017-10-24  54040  54700  54780  54040   5750000.0 -0.0048
2017-10-25  53900  54040  54420  53700   5870000.0 -0.0026
2017-10-26  52400  53720  53900  52400   9760000.0 -0.0278
2017-10-27  53080  52400  53320  52140   7390000.0  0.0130
2017-10-30  54040  53780  54320  53700   8190000.0  0.0181
2017-10-31  55080  54060  55440  53500  13300000.0  0.0192
2017-11-01  57220  57500  57500  56180  14280000.0  0.0389
2017-11-02  57060  57500  57520  56760  10180000.0 -0.0028
2017-11-03  56380  57060  57140  55860   9930000.0 -0.0119
2017-11-06  56380  56380  56500  55340   8960000.0  0.0000
2017-11-07  56100  56380  56920  55860   7460000.0 -0.0050
2017-11-08  56760  56100  57060  55860   8360000.0  0.0118
2017-11-09  56340  56920  56920  55900  11990000.0 -0.0074
2017-11-10  56400  55800  56540  55780   6640000.0  0.0011
2017-11-13  56380  56400  56800  56100   7470000.0 -0.0004
2017-11-14  55920  56380  56740  55920   6720000.0 -0.0082
2017-11-15  55340  55920  56320  55320   8750000.0 -0.0104
2017-11-16  55780  55440  56000  55400   7620000.0  0.0080
2017-11-17  55820  56400  56880  55820  10370000.0  0.0007
2017-11-20  55200  55900  55980  55200   9450000.0 -0.0111
...           ...    ...    ...    ...         ...     ...
2018-08-24  46150  45900  46400  45550   6440000.0 -0.0011
2018-08-26  46150  46150  46150  46150         0.0  0.0000
2018-08-27  46300  46100  46550  46000   5110000.0  0.0033
2018-08-28  46550  46800  46950  46300   7230000.0  0.0054
2018-08-29  46800  46750  46800  46400   5500000.0  0.0054
2018-08-30  47650  46950  47950  46700  12160000.0  0.0182
2018-08-31  48450  47100  48450  47000  13510000.0  0.0168
2018-09-02  48450  48450  48450  48450         0.0  0.0000
2018-09-03  47450  48200  48300  47300   7910000.0 -0.0206
2018-09-04  47650  47550  47800  47200   6610000.0  0.0042
2018-09-05  46600  47300  47450  46400   9100000.0 -0.0220
2018-09-06  46100  46200  46400  45800   8570000.0 -0.0107
2018-09-07  44900  44500  45200  44400  17730000.0 -0.0260
2018-09-09  44900  44900  44900  44900         0.0  0.0000
2018-09-10  45500  45450  45550  45000   7870000.0  0.0134
2018-09-11  45050  45550  45900  45050   7810000.0 -0.0099
2018-09-12  44550  44900  45100  44500  11170000.0 -0.0111
2018-09-13  44050  44550  44750  44000  17930000.0 -0.0112
2018-09-14  45850  45000  45850  44900  12030000.0  0.0409
2018-09-16  45850  45850  45850  45850         0.0  0.0000
2018-09-17  45150  45550  45800  44900   8100000.0 -0.0153
2018-09-18  45500  44950  45900  44700   8970000.0  0.0078
2018-09-19  46150  46000  46200  45700   9260000.0  0.0143
2018-09-20  47250  46850  47600  46400  13400000.0  0.0238
2018-09-21  47400  46550  47550  46550  14390000.0  0.0032
2018-09-26  47400  47400  47400  47400         0.0  0.0000
2018-09-27  47500  46950  47500  46450  15260000.0  0.0021
2018-09-28  46450  47250  47250  46300  10810000.0 -0.0221
2018-09-30  46450  46450  46450  46450         0.0  0.0000
2018-10-01  46400  46600  46700  45800   5760000.0 -0.0011

[259 rows x 6 columns]

In [121]:
# import FinanceDataReader as fdr

# KS11 (KOSPI 지수), 
ks_df = fdr.DataReader('KS11','2017-10-11','2018-10') # 삼성전자 171010데이터 오류
ks_df['Close']
ks_df.count()

Close     239
Open      239
High      239
Low       239
Volume    239
Change    239
dtype: int64

In [124]:
merged_df = pd.merge(stock_df, ks_df, left_index=True,right_index=True)
merged_df
# merged_df.to_csv('./datas/merged.csv')

,Close_x,Open_x,High_x,Low_x,Volume_x,Change_x,Close_y,Open_y,High_y,Low_y,Volume_y,Change_y
Date,,,,,,,,,,,,
2017-10-11,54640,53600,54760,53340,12900000.0,0.0348,2458.16,2442.49,2458.16,2439.81,201770.0,0.0100
2017-10-12,54800,54840,55160,54100,13730000.0,0.0029,2474.76,2461.70,2474.76,2459.48,256210.0,0.0068
2017-10-13,54000,54540,54840,53780,12520000.0,-0.0146,2473.62,2473.65,2479.73,2468.14,234800.0,-0.0005
2017-10-16,53920,53980,54860,53760,8960000.0,-0.0015,2480.05,2483.17,2487.71,2470.24,224410.0,0.0026
2017-10-17,54800,54020,55380,54000,10570000.0,0.0163,2484.37,2484.96,2487.88,2478.76,199050.0,0.0017
2017-10-18,54760,54820,55240,54040,10030000.0,-0.0007,2482.91,2481.53,2490.58,2475.67,244250.0,-0.0006
2017-10-19,52980,54700,54700,52980,11970000.0,-0.0325,2473.06,2485.72,2490.94,2468.67,236630.0,-0.0040
2017-10-20,53840,52800,54100,52800,7860000.0,0.0162,2489.54,2477.30,2489.54,2476.88,313210.0,0.0067
2017-10-23,54300,54600,54640,54000,8300000.0,0.0085,2490.05,2497.65,2500.33,2485.48,274200.0,0.0002
2017-10-24,54040,54700,54780,54040,5750000.0,-0.0048,2490.49,2489.31,2497.35,2487.17,232010.0,0.0002
2017-10-25,53900,54040,54420,53700,5870000.0,-0.0026,2492.50,2495.87,2497.41,2481.48,599430.0,0.0008
2017-10-26,52400,53720,53900,52400,9760000.0,-0.0278,2480.63,2489.60,2495.99,2480.63,646880.0,-0.0048
2017-10-27,53080,52400,53320,52140,7390000.0,0.0130,2496.63,2485.44,2499.15,2479.67,511230.0,0.0064
2017-10-30,54040,53780,54320,53700,8190000.0,0.0181,2501.93,2513.87,2513.87,2497.42,342010.0,0.0021
2017-10-31,55080,54060,55440,53500,13300000.0,0.0192,2523.43,2500.21,2528.32,2498.05,313790.0,0.0086
2017-11-01,57220,57500,57500,56180,14280000.0,0.0389,2556.47,2535.97,2556.47,2535.83,361800.0,0.0131
2017-11-02,57060,57500,57520,56760,10180000.0,-0.0028,2546.36,2560.34,2561.63,2542.02,527730.0,-0.0040
2017-11-03,56380,57060,57140,55860,9930000.0,-0.0119,2557.97,2558.37,2558.37,2539.72,292770.0,0.0046
2017-11-06,56380,56380,56500,55340,8960000.0,0.0000,2549.41,2557.29,2559.90,2529.94,221190.0,-0.0033
2017-11-07,56100,56380,56920,55860,7460000.0,-0.0050,2545.44,2548.30,2554.13,2540.67,253920.0,-0.0016
2017-11-08,56760,56100,57060,55860,8360000.0,0.0118,2552.40,2534.48,2558.74,2533.73,277040.0,0.0027
2017-11-09,56340,56920,56920,55900,11990000.0,-0.0074,2550.57,2559.93,2559.93,2536.54,293540.0,-0.0007
2017-11-10,56400,55800,56540,55780,6640000.0,0.0011,2542.95,2541.18,2547.61,2534.60,291530.0,-0.0030
2017-11-13,56380,56400,56800,56100,7470000.0,-0.0004,2530.35,2548.27,2552.28,2527.20,266530.0,-0.0050
2017-11-14,55920,56380,56740,55920,6720000.0,-0.0082,2526.64,2532.55,2532.95,2520.99,287770.0,-0.0015
2017-11-15,55340,55920,56320,55320,8750000.0,-0.0104,2518.25,2525.60,2526.61,2511.76,398220.0,-0.0033
2017-11-16,55780,55440,56000,55400,7620000.0,0.0080,2534.79,2522.42,2538.28,2514.51,302930.0,0.0066
2017-11-17,55820,56400,56880,55820,10370000.0,0.0007,2533.99,2546.05,2559.10,2533.99,362190.0,-0.0003
2017-11-20,55200,55900,55980,55200,9450000.0,-0.0111,2527.67,2536.80,2542.62,2523.52,404260.0,-0.0025
2017-11-21,55280,55400,55840,55280,9920000.0,0.0014,2530.70,2533.85,2539.88,2525.96,484890.0,0.0012
...,...,...,...,...,...,...,...,...,...,...,...,...
2018-08-16,44250,43800,44650,43700,10070000.0,-0.0199,2240.80,2233.05,2244.08,2218.09,312520000.0,-0.0080
2018-08-17,44100,44050,44400,44050,6540000.0,-0.0034,2247.05,2244.61,2250.92,2240.14,238380000.0,0.0028
2018-08-20,43850,43500,44200,43500,7200000.0,-0.0057,2247.88,2257.35,2264.42,2245.06,271600000.0,0.0004
2018-08-21,44800,43700,44900,43700,9470000.0,0.0217,2270.06,2248.04,2272.86,2244.59,294340000.0,0.0099
2018-08-22,46100,45150,46200,44900,11630000.0,0.0290,2273.33,2273.68,2280.31,2268.91,269270000.0,0.0014
2018-08-23,46200,46150,46200,45700,6600000.0,0.0022,2282.60,2282.57,2282.88,2268.06,338390000.0,0.0041
2018-08-24,46150,45900,46400,45550,6440000.0,-0.0011,2293.21,2276.16,2295.22,2271.35,347290000.0,0.0046
2018-08-27,46300,46100,46550,46000,5110000.0,0.0033,2299.30,2297.32,2302.87,2289.41,307040000.0,0.0027
2018-08-28,46550,46800,46950,46300,7230000.0,0.0054,2303.12,2312.14,2314.60,2299.45,276890000.0,0.0017
2018-08-29,46800,46750,46800,46400,5500000.0,0.0054,2309.03,2304.66,2309.88,2300.21,268210000.0,0.0026
2018-08-30,47650,46950,47950,46700,12160000.0,0.0182,2307.35,2313.11,2320.85,2305.46,286930000.0,-0.0007
2018-08-31,48450,47100,48450,47000,13510000.0,0.0168,2322.88,2298.13,2322.88,2295.72,255910000.0,0.0067
2018-09-03,47450,48200,48300,47300,7910000.0,-0.0206,2307.03,2317.93,2318.72,2302.17,230510000.0,-0.0068
2018-09-04,47650,47550,47800,47200,6610000.0,0.0042,2315.72,2308.96,2317.74,2302.17,277010000.0,0.0038
2018-09-05,46600,47300,47450,46400,9100000.0,-0.0220,2291.77,2310.90,2315.43,2288.01,358190000.0,-0.0103
2018-09-06,46100,46200,46400,45800,8570000.0,-0.0107,2287.61,2288.80,2298.47,2284.50,387510000.0,-0.0018
2018-09-07,44900,44500,45200,44400,17730000.0,-0.0260,2281.58,2278.08,2286.82,2264.90,357560000.0,-0.0026
2018-09-10,45500,45450,45550,45000,7870000.0,0.0134,2288.66,2277.35,2289.38,2276.60,312610000.0,0.0031
2018-09-11,45050,45550,45900,45050,7810000.0,-0.0099,2283.20,2286.91,2295.76,2275.13,368210000.0,-0.0024
2018-09-12,44550,44900,45100,44500,11170000.0,-0.0111,2282.92,2286.28,2289.66,2271.00,336830000.0,-0.0001
2018-09-13,44050,44550,44750,44000,17930000.0,-0.0112,2286.23,2285.28,2291.51,2281.63,301310000.0,0.0014
2018-09-14,45850,45000,45850,44900,12030000.0,0.0409,2318.25,2304.70,2318.65,2304.15,292240000.0,0.0140
2018-09-17,45150,45550,45800,44900,8100000.0,-0.0153,2303.01,2314.55,2314.55,2295.26,343170000.0,-0.0066
2018-09-18,45500,44950,45900,44700,8970000.0,0.0078,2308.98,2287.73,2310.97,2287.42,309240000.0,0.0026
2018-09-19,46150,46000,46200,45700,9260000.0,0.0143,2308.46,2319.22,2319.22,2301.79,350950000.0,-0.0002
2018-09-20,47250,46850,47600,46400,13400000.0,0.0238,2323.45,2314.41,2334.04,2311.56,289080000.0,0.0065
2018-09-21,47400,46550,47550,46550,14390000.0,0.0032,2339.17,2332.04,2339.17,2325.12,321700000.0,0.0068
2018-09-27,47500,46950,47500,46450,15260000.0,0.0021,2355.43,2331.70,2355.43,2331.70,279230000.0,0.0070
2018-09-28,46450,47250,47250,46300,10810000.0,-0.0221,2343.07,2356.13,2356.62,2337.47,317870000.0,-0.0052
2018-10-01,46400,46600,46700,45800,5760000.0,-0.0011,2338.88,2349.64,2352.11,2333.32,272610.0,-0.0018

https://m.blog.naver.com/PostView.nhn?blogId=wooooo2&logNo=221113274819&proxyReferer=&proxyReferer=https%3A%2F%2Fwww.google.co.kr%2F

In [125]:
def linreg(x,y): 
    x = sm.add_constant(x) 
    model = regression.linear_model.OLS(y,x).fit() 
    x = x[:,1] 
    return model.params[0], model.params[1] 

X = list(merged_df['Change_y'])
Y = list(merged_df['Change_x']) # 지수

In [126]:
len(X)

235

In [127]:

alpha, beta = linreg(X,Y) 
print('alpha:' + str(alpha)) 
print('beta:' + str(beta))

alpha:-0.00016218125667347822
beta:1.5885540723537184